### ISSUE TITLE
Better default onGMCP function

### ISSUE THREAD

**Issue by NexusUnleashed** [keneanung/nexus-event-bus#236]
Recommend revising the packaged onGMCP function to a more functional starter version like:

eventBus.raise(args.gmcp_method, args.gmcp_args);

This allows subscribing to GMCP events rather than GMCP as an event.
eventBus.subscribe('Char.Vitals', (args)=>{nexusclient.display_notice(`This is my hp: ${args.hp}`)})

**Comment by keneanung** [comment]
That should be already in there: https://github.com/keneanung/nexus-event-bus/blob/development/webpack/webpack.ts#L10 at least the provisions are there, but I haven't tested that explicitly yet...

**Comment by NexusUnleashed** [comment]
Ah, you are right that functionality is there. There is no way for a regular user to know those events are being raised out of the box. From a User's view the onGMCP is just raising an event named "onGMCP". That is what I assumed it was doing, and changed the onGMCP to the snippet above.

Recommend either revising to the snippet above or adding to the documentation to clarify how GMCP events are being handled out of the box. My preference is to change the onGMCP function in the nxs package for transparency.

**Comment by keneanung** [comment]
I moved the place where the event is raised to the suggested onGMCP event as well and documented their presence: https://keneanung.github.io/nexus-event-bus/docs/default_events
